services:
  - type: web
    name: hikerAid
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
