databases:
  - name: hikeraid-db
    plan: free
    region: frankfurt
    databaseName: hikeraid
    user: hikeraid

services:
  - type: web
    name: hikeraid
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hikeraid-db
          property: connectionString
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false
